name: StoneOplata
version: '${project.version}'
main: hgds.stoneoplata.StoneOplata
api-version: '1.17'
description: Выдача покупок с сайта на сервер по вебхуку (HMAC-SHA256)
author: hgds_2:
  stoneoplata:
    description: Управление плагином и тестовая выдача
    usage: /stoneoplata <reload|testpay> [аргументы]

permissions:
  stoneoplata.admin:
    description: Перезагрузка конфига и вебхука
    default: op
  stoneoplata.testpay:
    description: Тестовая выдача покупки (проверка выдачи без оплаты)
    default: op
