name: StoneOplata
version: '${project.version}'
main: hgds.stoneoplata.StoneOplata
description: Выдача покупок с сайта mcsaura.su на сервер по вебхуку (HMAC-SHA256)

commands:
  stoneoplata:
    description: Управление плагином и тестовая выдача
    usage: /stoneoplata <reload|testpay> [аргументы]

permissions:
  stoneoplata.admin:
    description: Перезагрузка конфига и вебхука
    default: op
  stoneoplata.testpay:
    description: Тестовая выдача покупки (проверка без оплаты)
    default: op
