name: StoneBosses
version: '1.0'
main: hgds.stonebosses.StoneBosses
api-version: '1.17'
commands:
  stonebosses:
    description: Основная команда StoneBosses
    aliases: [sb, bosses]
    usage: /stonebosses <start|reload>
permissions:
  stonebosses.admin:
    description: Административные права
    default: op
